databases:
  - name: nexellia
    databaseName: nexellia
    user: nexellia

services:
  - type: redis
    name: nexellia_redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu

  - type: web
    name: nexellia
    plan: free
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexellia_redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: nexellia
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false